apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: gcr.io/kupping/github.com/maiconpintoabreu/kupping/frontend
    context: .
deploy:
  kubectl:
    manifests:
    - charts/configmap.yaml
    - charts/development.yaml
    - charts/service.yaml
    # - ngrok/charts/configmap.yaml
    # - ngrok/charts/development.yaml
    # - ngrok/charts/service.yaml
