apiVersion: v1
kind: Service
metadata:
  labels:
    app: ngrok-wernight
  name: ngrok-wernight-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ngrok-wernight
  sessionAffinity: None
  type: ClusterIP